version: "3.8"

services:
  digidar:
    build:
      context: ./digidar # adjust to your project folder name
      dockerfile: ../Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./digidar:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: digidar-dev
    develop:
      watch:
        - action: sync
          path: ./digidar/src
          target: /app/src
          ignore:
            - node_modules/
        - action: sync
          path: ./digidar/public
          target: /app/public
          ignore:
            - node_modules
